# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polycrate < Formula
  desc "Polycrate is a framework to build platforms."
  homepage "https://www.ayedo.de/"
  version "0.7.5"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.5/polycrate_0.7.5_darwin_arm64.tar.gz"
      sha256 "43a72e431e1e3175260c31c4d956b1da453290f998f1ed1ca1bc96c1a4ceb5f7"

      def install
        bin.install "polycrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.5/polycrate_0.7.5_darwin_amd64.tar.gz"
      sha256 "6557c02b1ccd05517b047f05241ba6a6507d02f26ad9f22e83a4932285258c43"

      def install
        bin.install "polycrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.5/polycrate_0.7.5_linux_arm64.tar.gz"
      sha256 "a2a4f62f459437dc2316683acdfde1e93338d0fc7e16e35d7405c773bc77dbc7"

      def install
        bin.install "polycrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.5/polycrate_0.7.5_linux_amd64.tar.gz"
      sha256 "c3fe6dacdc2aee5d51ba95c8539957aa805348544548a6ebecd2048bc72b3314"

      def install
        bin.install "polycrate"
      end
    end
  end

  depends_on "docker" => :optional
end
