# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polycrate < Formula
  desc "Polycrate is a framework to build platforms."
  homepage "https://www.ayedo.de/"
  version "0.7.4"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.4/polycrate_0.7.4_darwin_arm64.tar.gz"
      sha256 "86ae82ae86dd4af428c5a98d2f1081ffb3879214c417fcd8f08e349872c0605b"

      def install
        bin.install "polycrate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.4/polycrate_0.7.4_darwin_amd64.tar.gz"
      sha256 "f6b72d0e482188ef5eedea389b3338299b8bd3163740705c86a5c67de0690c09"

      def install
        bin.install "polycrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.4/polycrate_0.7.4_linux_amd64.tar.gz"
      sha256 "7235da300da496da54ecef597ed53801a665c68aeb58df3b5bb50d94d303cd45"

      def install
        bin.install "polycrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/polycrate/polycrate/releases/download/v0.7.4/polycrate_0.7.4_linux_arm64.tar.gz"
      sha256 "feaaef3aca5f143e003af6efe359f2f14e4044eca3aa637c62a407d5869a8a58"

      def install
        bin.install "polycrate"
      end
    end
  end

  depends_on "docker" => :optional
end
